name: myringover-desktopv2
version: '0.1'
summary: Hello World Electron app
description: |
  Simple Hello World Electron app as an example
base: core18
confinement: strict
grade: stable

apps:
  electron-packager-hello-world:
    command: electron-quick-start/electron-quick-start --no-sandbox
    extensions: [gnome-3-34]
    plugs:
    - browser-support
    - network
    - network-bind
    - pulseaudio
    - home
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to ensure
      # libappindicator has readable resources.
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  electron-quick-start:
    plugin: nil
    source: .
    override-build: |
        npm install electron electron-packager
        npx electron-packager . myringover-desktopv2 --overwrite --platform=linux --output=release-build --prune=true
        cp -rv ./myringover-desktopv2-linux-* $SNAPCRAFT_PART_INSTALL/myringover-desktopv2
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4
